title: இங்க என்ன சொல்லுது?
tagline: இங்க என்ன சொல்லுதோ அதை உங்களுக்கு சொல்றேன். கேளுங்க. பிடிச்சிருந்தா, நண்பர்களுக்கு சொல்லுங்க. நன்றி வணக்கம் !!!
author: பிரேம்குமார் மாசிலாமணி
email: tamil-podcast@smileprem.com
url: http://localhost:4000
copyright: copyleft @ 2009.

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 1000

permalink: /:title/

img-path: http://localhost:4000/public/images
audio-path: http://localhost:4000/public/audio

english-blog: https://blog.smileprem.com/
tamil-blog: https://tamil.smileprem.com/